# Generated by Django 3.0.6 on 2021-03-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Vacancy',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
    ]
