# Generated by Django 3.0.6 on 2021-03-17 19:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210317_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
